# creates service account with permissions to access prometheus metrics
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cluster-health-analyzer-thanos-querier
  namespace: openshift-cluster-health-analyzer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-health-analyzer-thanos-querier
subjects:
  - kind: ServiceAccount
    name: cluster-health-analyzer-thanos-querier
    namespace: openshift-cluster-health-analyzer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-health-analyzer:system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: cluster-health-analyzer-thanos-querier
    namespace: openshift-cluster-health-analyzer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-alerts-view
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers/api
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - "config.openshift.io"
  resources:
  - clusteroperators
  verbs:
  - get
  - list
- apiGroups:
  - "kubevirt.io"
  resources:
  - kubevirts
  verbs:
  - get
  - list
- apiGroups:
  - "machineconfiguration.openshift.io"
  resources:
  - machineconfigpools
  verbs:
  - get
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-health-analyzer-alerts-binding
subjects:
  - kind: ServiceAccount
    name: cluster-health-analyzer-thanos-querier
    namespace: openshift-cluster-health-analyzer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-alerts-view
---

