apiVersion: v1
kind: ConfigMap
metadata:
  name: 'components-config'
  namespace: openshift-cluster-health-analyzer
data: 
  components.yaml: |
    components:
    - name: control-plane
      children:
      - name: nodes
        objects:
        - resource: nodes
          selectors:
          - matchLabels:
              node-role.kubernetes.io/control-plane: []
      - name: capacity
        children:
        - name: cpu
          alerts:
            selectors:
            - matchLabels:
                alertname: ["KubeCPUOvercommit","HighOverallControlPlaneCPU"]
        - name: memory
          alerts:
            selectors:
            - matchLabels:
                alertname: ["HighOverallControlPlaneMemory"]
      - name: operators
        children:
        - name: authentication
        - name: baremetal
        - name: cloud-controller-manager
        - name: cloud-credential
        - name: cluster-autoscaler
        - name: config-operator
        - name: console
        - name: control-plane-machine-set
        - name: csi-snapshot-controller
        - name: dns
        - name: etcd
          alerts:
            selectors:
            - matchLabels:
                namespace: ["openshift-etcd","openshift-etcd-operator"]
        - name: image-registry
        - name: ingress
        - name: insights
        - name: kube-apiserver
        - name: kube-controller-manager
        - name: kube-scheduler
        - name: kube-storage-version-migrator
        - name: machine-api
        - name: machine-approver
        - name: machine-config
        - name: marketplace
        - name: monitoring
        - name: network
        - name: node-tuning
        - name: olm
        - name: openshift-apiserver
        - name: openshift-controller-manager
        - name: openshift-samples
        - name: operator-lifecycle-manager
        - name: operator-lifecycle-manager-catalog
        - name: operator-lifecycle-manager-packageserver
        - name: service-ca
        - name: storage
    - name: addons
      children:
      - name: kubevirt
        alerts:
          selectors:
          - matchLabels:
              kubernetes_operator_part_of: ["kubevirt"]
          - matchLabels:
              namespace: ["openshift-cnv"]
        objects:
        - group: kubevirt.io
          resource: kubevirts
binaryData: {}
immutable: false