apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cluster-health-analyzer
  name: cluster-health-analyzer
  namespace: cluster-health-analyzer
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: cluster-health-analyzer
  type: ClusterIP