# creates service account with permissions to access prometheus metrics
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cluster-health-analyzer-mcp-thanos-querier
  namespace: openshift-cluster-observability-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-health-analyzer-mcp-thanos-querier
subjects:
  - kind: ServiceAccount
    name: cluster-health-analyzer-mcp-thanos-querier
    namespace: openshift-cluster-observability-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-health-analyzer-mcp:system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: cluster-health-analyzer-mcp-thanos-querier
    namespace: openshift-cluster-observability-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
